print ("hello")
raise SecondaryException() from primary_exception
